#!/bin/sh

trap "" HUP

/etc/init.d/nulldm stop

if [ -e /etc/default/usbwatcher ]; then
	esplash -i /etc/default/usbwatcher
fi


STORAGE=/dev/mtdblock_storage
SD=`awk '/media\/sd/{print $1}' /proc/mounts`
if [ x${SD} != x"" ];
then
	FILE=${STORAGE},${SD}
else
	FILE=${STORAGE}
fi

umount /media/sd
umount /mnt/storage

rmmod g_ether
modprobe g_file_storage file=${FILE} stall=0 removable=1 serial=000000000516

echo STATE=mass_storage > /var/lib/usbwatcher/state
